ports = [
    "xproto@7.0.23",
    "libXau@1.0.7",
    "libpciaccess@0.16",
    "xcb-proto@1.6",
    "libdrm@2.4.100",
    "libxcb@1.5",
    "libxshmfence@1.3",
    "libexpat@R_2_2_7",
    "openssl@openssl-3.4.0",
    "glproto@1.4.14",
    "dri2proto@dri2proto-2.8",
    "x11@libX11-1.8.4",
    "mesa@12.0.5"
]