ports = ["gflags@2.2.2", "x264@stable"]

[optimize_msvc]
    debug = "/MDd /Zi /Od /Ob0 /RTC1"
    release = "/MD /O2 /Ob2 /DNDEBUG"
    relwithdebinfo = "/MD /Zi /O2 /Ob1 /DNDEBUG"
    minsizerel = "/MD /O1 /Ob1 /DNDEBUG"

[optimize_gcc]
    debug = "-O0 -g3 -fno-omit-frame-pointer"
    release = "-O3 -DNDEBUG -march=native"
    relwithdebinfo = "-O2 -g -DNDEBUG"
    minsizerel = "-Os -DNDEBUG"

[optimize_clang]
    debug = "-O0 -g3 -fno-omit-frame-pointer"
    release = "-O3 -DNDEBUG -march=native"
    relwithdebinfo = "-O2 -g -DNDEBUG"
    minsizerel = "-Oz -DNDEBUG"