ports = [
    "x264@stable",
    "sqlite3@3.49.0",
    "ffmpeg@3.4.13",
    "zlib@1.3.1",
    "opencv@4.11.0"
]

cmake_vars = [
    "CMAKE_VAR1=value1",
    "CMAKE_VAR2=value2"
]

env_vars = [
    "ENV_VAR1=/home/ubuntu/ccache"
]

micro_vars = [
    "MICRO_VAR1=111",
    "MICRO_VAR2"
]