ports = [
    "sqlite3@3.49.0",
    "ffmpeg@3.4.13",
    "zlib@1.3.1",
    "opencv@4.11.0"
]

vars = [
    "CMAKE_VAR1=value1",
    "CMAKE_VAR2=value2"
]

envs = [
    "ENV_VAR1=/home/ubuntu/ccache"
]

micros = [
    "MICRO_VAR1=111",
    "MICRO_VAR2"
]

flags = [
    "-std=c++17"
]

[optimize_windows]
    debug = "/MDd /Zi /Ob0 /Od /RTC1"
    release = "/MD /O2 /Ob2 /DNDEBUG"
    relwithdebinfo = "/MD /Zi /O2 /Ob1 /DNDEBUG"
    minsizerel = "/MD /O1 /Ob1 /DNDEBUG"

[optimize_linux]
    debug = "-g"
    release = "-O3"
    relwithdebinfo = "-O2 -g"
    minsizerel = "-Os"