target_platform = "x86_64-linux-ubuntu-22.04-gcc-11.5.0"
build_type = "Release"
python_version = "3.10.12"
ports = ["boost@1.83.0", "eigen@3.4.0", "tinyxml2@10.0.0", "libzmq@4.3.5", "libzmq@4.3.5"]
vars = []
envs = []
macros = []
