namespace = "FFmpeg"

[linux_shared]
[[linux_shared.components]]
component = "avutil"
soname = "libavutil.so.55"
filename = "libavutil.so.55.78.100"
dependencies = []

[[linux_shared.components]]
component = "avcodec"
soname = "libavcodec.so.57"
filename = "libavcodec.so.57.107.100"
dependencies = ["avutil"]

[[linux_shared.components]]
component = "avdevice"
soname = "libavdevice.so.57"
filename = "libavdevice.so.57.10.100"
dependencies = ["avformat", "avutil"]

[[linux_shared.components]]
component = "avfilter"
soname = "libavfilter.so.6"
filename = "libavfilter.so.6.107.100"
dependencies = ["swscale", "swresample"]

[[linux_shared.components]]
component = "avformat"
soname = "libavformat.so.57"
filename = "libavformat.so.57.83.100"
dependencies = ["avcodec", "avutil"]

[[linux_shared.components]]
component = "postproc"
soname = "libpostproc.so.54"
filename = "libpostproc.so.54.7.100"
dependencies = ["avcodec", "swscale", "avutil"]

[[linux_shared.components]]
component = "swresample"
soname = "libswresample.so.2"
filename = "libswresample.so.2.9.100"
dependencies = ["avcodec", "swscale", "avutil", "avformat"]

[[linux_shared.components]]
component = "swscale"
soname = "libswscale.so.4"
filename = "libswscale.so.4.8.100"
dependencies = ["avcodec", "avutil", "avformat"]

[windows_shared]
[[windows_shared.components]]
component = "avutil"
impname = "avutil.lib"
filename = "avutil-55.dll"
dependencies = []

[[windows_shared.components]]
component = "avcodec"
impname = "avcodec.lib"
filename = "avcodec-57.dll"
dependencies = ["avutil"]

[[windows_shared.components]]
component = "avdevice"
impname = "avdevice.lib"
filename = "avdevice-57.dll"
dependencies = ["avformat", "avutil"]

[[windows_shared.components]]
component = "avfilter"
impname = "avfilter.lib"
filename = "avfilter-6.dll"
dependencies = ["swscale", "swresample"]

[[windows_shared.components]]
component = "avformat"
impname = "avformat.lib"
filename = "avformat-57.dll"
dependencies = ["avcodec", "avutil"]

[[windows_shared.components]]
component = "postproc"
impname = "postproc.lib"
filename = "postproc-54.dll"
dependencies = ["avcodec", "swscale", "avutil"]

[[windows_shared.components]]
component = "swresample"
impname = "swresample.lib"
filename = "swresample-2.dll"
dependencies = ["avcodec", "swscale", "avutil", "avformat"]

[[windows_shared.components]]
component = "swscale"
impname = "swscale.lib"
filename = "swscale-4.dll"
dependencies = ["avcodec", "avutil", "avformat"]