[package]
url = "https://ffmpeg.org/releases/ffmpeg-3.4.13.tar.xz"
ref = "3.4.13"

# ================ build for Linux ================ #
[[build_configs]]
pattern = "*linux*"
options = [
    "--sysroot=${SYSROOT}",
    "--cross-prefix=${CROSS_PREFIX}",
    "--arch=${SYSTEM_PROCESSOR}",
    "--target-os=linux",
    "--pkg-config=pkgconf",
    "--enable-cross-compile",
    "--disable-programs",
    "--disable-doc",
    "--enable-pic",
    "--enable-gpl",
    "--enable-libx264",
]
dependencies = ["x264@stable"]

# ================ build for Windows ================ #
[[build_configs]]
pattern = "*windows*"
options = [
    "--toolchain=msvc",
    "--target-os=win64",
    "--pkg-config=pkgconf",
    "--disable-programs",
    "--disable-doc",
    "--enable-pic",
    "--enable-gpl",
    "--enable-libx264",
]
dependencies = ["x264@stable"]