[rootfs]
url = "https://github.com/cppbuildenv/buildenv_test_resource/releases/download/v1.0.0/gcc-arm-8.3-2019.02-x86_64-aarch64-linux-gnu.tar.xz"
path = "sysroot-glibc-8.3-2019.02-x86_64-aarch64-linux-gnu"
pkg_config_path = ["usr/lib64/pkgconfig"]

[toolchain]
url = "https://github.com/cppbuildenv/buildenv_test_resource/releases/download/v1.0.0/gcc-arm-8.3-2019.02-x86_64-aarch64-linux-gnu.tar.xz"
path = "gcc-arm-8.3-2019.02-x86_64-aarch64-linux-gnu/bin"
name = "gcc"
version = "8.3"
system_name = "Linux"
system_processor = "aarch64"
host = "aarch64-linux-gnu"
toolchain_prefix = "aarch64-linux-gnu-"
cc = "aarch64-linux-gnu-gcc"
cxx = "aarch64-linux-gnu-g++"
fc = "aarch64-linux-gnu-gfortran"
ld = "aarch64-linux-gnu-ld"
ranlib = "aarch64-linux-gnu-ranlib"
ar = "aarch64-linux-gnu-ar"
nm = "aarch64-linux-gnu-nm"
objdump = "aarch64-linux-gnu-objdump"
strip = "aarch64-linux-gnu-strip"