[rootfs]
url = "https://github.com/cppbuildenv/buildenv_test_resource/releases/download/v1.0.0/sysroot-glibc-9.2-2019.12-x86_64-aarch64-linux-gnu.tar.gz"
path = "sysroot-glibc-9.2-2019.12-x86_64-aarch64-linux-gnu"
pkg_config_path = [
    "usr/lib/pkgconfig",
    "usr/share/pkgconfig"
]

[toolchain]
url = "https://github.com/cppbuildenv/buildenv_test_resource/releases/download/v1.0.0/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.gz"
path = "gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu/bin"
name = "gcc"
version = "9.2"
system_name = "Linux"
system_processor = "aarch64"
host = "aarch64-none-linux-gnu"
toolchain_prefix = "aarch64-none-linux-gnu-"
cc = "aarch64-none-linux-gnu-gcc"
cxx = "aarch64-none-linux-gnu-g++"
fc = "aarch64-none-linux-gnu-gfortran"
ld = "aarch64-none-linux-gnu-ld"
ranlib = "aarch64-none-linux-gnu-ranlib"
ar = "aarch64-none-linux-gnu-ar"
nm = "aarch64-none-linux-gnu-nm"
objdump = "aarch64-none-linux-gnu-objdump"
strip = "aarch64-none-linux-gnu-strip"