[toolchain]
  url = "https://github.com/celer-pkg/test-conf/releases/download/resource/qnx800.tar.xz"
  sha256 = "3e64f39e6a4900efdc06187b48483f71f6ebba04878505c853b6df709c84a42f"
  path = "qnx800/host/linux/x86_64/usr/bin"
  name = "qcc"
  version = "12.2.0"
  system_name = "qnx"
  system_processor = "aarch64"
  host = "aarch64-nto-qnx"
  crosstool_prefix = "ntoaarch64-"
  cc = "ntoaarch64-gcc"
  cxx = "ntoaarch64-g++"
  ld = "ntoaarch64-ld"
  ranlib = "ntoaarch64-ranlib"
  ar = "ntoaarch64-ar"
  nm = "ntoaarch64-nm"
  objdump = "ntoaarch64-objdump"
  strip = "ntoaarch64-strip"
  c_compiler_target = "gcc_ntoaarch64le"
  cxx_compiler_target = "gcc_ntoaarch64le_cxx"
  envs = [
    "QNX_CONFIGURATION=${TOOLCHAIN_DIR}/.qnx",
    "QNX_CONFIGURATION_EXCLUSIVE=${TOOLCHAIN_DIR}/.qnx",
  ]
