[rootfs]
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/sysroot-glibc-9.2-2019.12-x86_64-aarch64-linux-gnu.tar.gz"
path = "sysroot-glibc-9.2-2019.12-x86_64-aarch64-linux-gnu"
pkg_config_path = ["usr/lib/pkgconfig", "usr/share/pkgconfig"]
lib_dirs = ["usr/lib"]

[toolchain]
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.gz"
path = "gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu/bin"
name = "gcc"
version = "9.2"
system_name = "Linux"
system_processor = "aarch64"
host = "aarch64-none-linux-gnu"
crosstool_prefix = "aarch64-none-linux-gnu-"
c_standard = "gnu99"
cxx_standard = "c++17"
cc = "aarch64-none-linux-gnu-gcc"
cxx = "aarch64-none-linux-gnu-g++"
fc = "aarch64-none-linux-gnu-gfortran"
ld = "aarch64-none-linux-gnu-ld"
ranlib = "aarch64-none-linux-gnu-ranlib"
ar = "aarch64-none-linux-gnu-ar"
nm = "aarch64-none-linux-gnu-nm"
objdump = "aarch64-none-linux-gnu-objdump"
strip = "aarch64-none-linux-gnu-strip"
