[toolchain]
  url = "https://github.com/celer-pkg/test-conf/releases/download/resource/LLVM-21.1.4-win64.zip"
  sha256 = "3f1e13be63d3bf8476bf794c6285998c32377ae7aaa2b3419216fe92e6d8f7fb"
  path = "LLVM-21.1.4-win64/bin"
  name = "clang"
  version = "21.1.4"
  system_name = "Windows"
  system_processor = "x86_64"
  host = "x86_64-w64-windows-gnu"
  cc = "clang.exe"
  cxx = "clang++.exe"
  ar = "llvm-ar.exe"
  ld = "ld.lld.exe"
  cpp = "clang-cpp.exe"
  gcov = "llvm-cov.exe"
  nm = "llvm-nm.exe"
  objdump = "llvm-objdump.exe"
  strip = "llvm-strip.exe"
  objcopy = "llvm-objcopy.exe"
  as = "llvm-as.exe"