[rootfs]
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/ubuntu-base-22.04.5-base-amd64.tar.gz"
path = "ubuntu-base-22.04.5-base-amd64"
pkg_config_path = [
    "usr/lib/x86_64-linux-gnu/pkgconfig",
]

[toolchain]
url = "https://github.com/celer-pkg/test-conf/releases/download/resource/gcc-11.5.0.tar.gz"
path = "gcc-11.5.0/bin"
name = "gcc"
version = "11.5"
system_name = "Linux"
system_processor = "x86_64"
host = "x86_64-linux-gnu"
crosstool_prefix = "x86_64-linux-gnu-"
c_standard = "gnu99"
cxx_standard = "c++17"
cc = "x86_64-linux-gnu-gcc"
cxx = "x86_64-linux-gnu-g++"
