[rootfs]
url = "https://github.com/cppbuildenv/buildenv_test_resource/releases/download/v1.0.0/ubuntu-base-22.04.5-base-amd64.tar.gz"
path = "ubuntu-base-22.04.5-base-amd64"
pkg_config_path = [
    "usr/lib/x86_64-linux-gnu/pkgconfig",
]

[toolchain]
url = "https://github.com/cppbuildenv/buildenv_test_resource/releases/download/v1.0.0/gcc-11.5.0.tar.gz"
path = "gcc-11.5.0/bin"
name = "gcc"
version = "11.5"
system_name = "Linux"
system_processor = "x86_64"
host = "x86_64-linux-gnu"
crosstool_prefix = "x86_64-linux-gnu-"
cc = "x86_64-linux-gnu-gcc"
cxx = "x86_64-linux-gnu-g++"
