[package]
url = "https://ffmpeg.org/releases/ffmpeg-5.1.6.tar.xz"
ref = "5.1.6"

# ================ build for Linux ================ #
[[build_configs]]
pattern = "*linux*"
options = [
    "--sysroot=${SYSROOT}",
    "--cross-prefix=${CROSS_PREFIX}",
    "--arch=${SYSTEM_PROCESSOR}",
    "--target-os=linux",
    "--pkg-config=pkgconf",
    "--enable-cross-compile",
    "--disable-programs",
    "--disable-doc",
    "--enable-libx264",
    "--disable-libx265",
    "--enable-pic",
    "--enable-gpl",
]
dependencies = ["x264@stable"]

# ================ build for Windows ================ #
[[build_configs]]
pattern = "*windows*"
options = [
    "--arch=${SYSTEM_PROCESSOR}",
    "--enable-runtime-cpudetect",
    "--disable-autodetect",
    "--target-os=win32",
    "--enable-cross-compile",
    "--enable-w32threads",
    "--enable-mediafoundation",
    "--pkg-config=pkgconf",
    "--toolchain=msvc",
    "--disable-programs",
    "--disable-doc",
    "--enable-libx264",
    "--enable-pic",
    "--enable-gpl",
]
dependencies = ["x264@stable"]
